amufr/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('admins.urls')),
    path('student/',include('student.urls',namespace="student")),
    path('faculty/',include('faculty.urls',namespace="faculty"))

]

student/urls.py
from . import views
from django.urls import path

app_name="student"


urlpatterns=[
    path('login_student',views.login_student,name="login_student"),
    path('forgotpwS',views.forgotpwS,name="forgotpwS"),
    path('student_home',views.student_home,name="student_home"),
    path('student_profile',views.student_profile,name="student_profile"),
    path('student_authentication',views.student_authentication,name="student_authentication"),
    path('student_msg',views.student_msg,name="student_msg"),
    path('student_chat',views.student_chat,name="student_chat"),
]

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render,redirect
import faculty
from faculty.models import Student,FacultyAuthentication

# Create your views here.
def login_student(request):
    error=''
    if request.method=='POST':
        stu_email=request.POST['s_email']
        stu_password=request.POST['s_password']
        try:
            user_data=Student.objects.get(email=stu_email,password=stu_password)
            request.session['student_id']=user_data.id
            request.session['dep']=user_data.dpt
            request.session['sem']=user_data.semester
            return redirect('student:student_home')
        except:
            error="invalid username or password"

    return render(request,'student/student_login.html',{'error':error})








def forgotpwS(request):
    return render(request,'student/student_forgot_pw.html')  






def student_home(request):
    student_name= request.session['student_id']
    student_display=Student.objects.get(id=student_name)
    return render(request,'student/student_home.html',{'stu':student_display})  





def student_profile(request):
    student_name= request.session['student_id']
    student_display=Student.objects.get(id=student_name)
    return render(request,'student/student_profile.html',{'stu':student_display})     






def student_authentication(request):
    student_name= request.session['student_id']
    student_display=Student.objects.get(id=student_name)
    return render(request,'student/student_authentication.html',{'stu':student_display}) 










def student_msg(request):
    data=FacultyAuthentication.objects.filter(ac_sem=request.session['sem'],ac_dpt=request.session['dep'])
    print(data)
    return render(request,'student/student_msg.html',{'data':data,})  







def student_chat(request):
    return render(request,'student/student_chat.html')     

student/templates/student/student_authentication.html
{% extends 'student/student_master.html' %}
{% block student_content %}
           
 
    <table class="form">
        <form>
            <h2 class="head" style="font-weight: bolder;
            font-family: 'Times New Roman', Times, serif;
            text-align: center;   
            padding-top: 30px;"><b> Please Enter the Authentication Code</b></h2>
               
                <tr>
                    <p class="des">Dear student, please enter your class authentication code to get to your attendance.This unique authentication code will be generated by the faculty to save the system from any student fraudulent activities.</p>
                </tr>
                <tr>
                    <td><label for="">Department:</label></td>
                 
                    <td><input type="text" class="form-control" name="" id="" placeholder="{{stu.dpt}}">
                     <!-- <select class="form-control" name="" id="">
                         <option value="">CSE</option>
                         <option value="">ECE</option>
                     </select> -->
                    </td>
                 </tr>


                 <tr >
                    <td><label for="">Semester:</label></td>
                 
                    <td><input type="text" class="form-control" name="" id="" placeholder="{{stu.semester}}">
                     <!-- <select class="form-control" name="" id="">
                         <option value="">1</option>
                         <option value="">2</option>
                         
                     </select> -->
                    </td>
                 </tr>
            
                <tr>
                   <td><label for="">Subject:</label></td>
                
                   <td>
                    <select class="form-control" name="" id="">
                        <option value="">Python</option>
                        <option value="">C</option>
                        <option value="">C++</option>
                        <option value="">Java</option>
                        <option value="">Electronics</option>
                        <option value="">Electrical</option>
                        <option value="">Mp & Mc</option>
                        <option value="">Instrumentaion</option>
                        
                    </select>
                   </td>
                </tr>
                <tr>
                   <td><label for="" class="second">Authentication Code:</label></td>
                   <td><input type="text" class=" second form-control" name="" id=""></td>
                </tr>
                <tr>
                    <td> <button type="button" style="margin-left: 150px;" class="third btn btn-dark">Submit</button></td>
                </tr>
                 

        </form>
    </table>

            


{% endblock%}

student/templates/student/student_chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="icon" type="images/x-icon" href="{% static 'images/metro1.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/reply.css' %}">

    <style>
       
body{
    margin: 0;
    
    background-image: url("{% static 'images/cls.webp' %}");
}

h1{
    font-weight: bolder;
    font-family: 'Times New Roman', Times, serif;
    text-align: center;   
    padding-top: 40px; 
}
p{
    text-decoration: none;
    font-size: 20px;
    font-weight: 600;
    margin-top: 40px;
    text-align: center;
    font-family: 'Times New Roman', Times, serif;
}

.main{

    width: 800px;
    height: 600px;
    margin-left: 380px;
    margin-top: 50px;
    background-color: rgba(255, 255, 255, 0.686);
    
}
 .table{
    border: none;
    width: 500px;
    margin-left: 130px;
    margin-top: 70px;
    border: none;
}
 

textarea{
    width: 400px;
    height: 100px;
    background-color: rgba(255, 255, 255, 0.518);
    border: solid 1px white;
}
.btn{
    background-color: black;
    color: #fff;
    width: 200px;
    margin-top: 30px;
}
.btn:hover{
    background-color: #fff;
    color: black;
    border: solid 2px black;
}
.btn1{
    margin-left: 210px;
   
}
.btn{
  margin-left: 300px;
}
     
input{
   border: solid 1px white;
   width: 400px;
}
     
td{
    font-size: large;
    font-weight: 400;
}   
    </style>
</head>
<body>
    <div class="body">
       <div class="shadow main">
             <h1>Contact Faculty</h1>
             <p>Talk with your faculties to resolve your problems.</p>
            
             <table class="table">
                <thead>
                  <tr>
                    <td >Name of faculty</td>
                    <td >:</td>
                    <td ><input type="text"></td>
                    
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Email</td>
                    <td>:</td>
                    <td><input type="text"></td>
                    
                  </tr>
                  <tr>
                    <td>Message</td>
                    <td>:</td>
                    <td><textarea name="" id="" cols="30" rows="10"></textarea></td>
                    
                  </tr>
                 
                </tbody>
              </table>
          <a href="" class="btn btn-light">Send</a>
         </div>
    </div>
</body>
</html>

student/templates/student/student_forgot_pw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
<style>
    
    .head{
        max-width: 600px;
        margin: 50px auto; 
        position: relative;
        box-shadow: 0 50px 50px 0px rgba(0,0,0,0.1);
        padding-top: 50px;
        background: linear-gradient(to right,hsl(204, 81%, 69%) 0%, #30f36b  100%);
        border-radius: 20px;
        text-align: center;
    }
    .mail{
        line-height: 30px;
        width: 350px;
    }
    

</style>
<body>
    


    <section class="head">
        <h2 class="title">Forgot password</h2>

        <div class="container">
            <div class="row">
                <div class="col-lg-12 pt-5">
                  <input type="text"  class="mail" name="" id="" placeholder="Email/Phone Number">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 pt-5">
                    <button type="button" class="btn btn-success">Change Password</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 pt-5">
                 <a href="" class="link">Back to Sign In</a><br><br><br>
                </div>
            </div>
     </section>
    
</body>
</html>

student/templates/student/student_home.html
{% extends 'student/student_master.html' %}
{% block student_content %}

<h1 style="font-weight: bolder;font-family: 'Times New Roman', Times, serif;text-align: center;padding-top: 250px;padding-left: 1px;">Welcome {{stu.name}}</h1>
{% endblock %}

student/templates/student/student_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script> 
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'js/login_student.js' %}"></script>

</head>
<style>
    .head{
        max-width: 1000px;
        margin: 50px auto; 
        position: relative;
        box-shadow: 0 50px 50px 0px rgba(0,0,0,0.1);
    }
    .head .title{
        font-style: initial;
        text-align: center;
        line-height: 40px;
        padding-bottom: 20px;
        padding-top: 20px;
        color:  black;
        background: linear-gradient(to right,hsl(204, 81%, 69%) 0%,#daf0b8 100%);
        
    }
    .head .dialog{
        color: grey;
        text-align: center;
    }  
    img{
        border-radius: 30px;
        height: 100px;
        width: 100px;
        justify-content: center;
        text-align: center;
    }
    .form-row{
        background-color: white;
        justify-content: center; 
       
    }
    .form-row{
        position: relative;
        margin: 20px 20px;
        justify-content: center;
        padding-left: 300px;
        padding-top: 0px;
    }
    .form-row .btn1{
        border: none;
        outline: none;
        height: 50px;
        width: 100%;
        background-color: black;
        color: white;
        border-radius: 4px;
        font-weight: bold;
    }
    .form-row .btn1:hover{
        background: white;
        border: 1px solid;
        color: black;
    }
    .aaaa{
        padding-left: 350px;
    }
       
    

</style>
<body>
    <section class="head">
        <h2 class="title">STUDENT LOGIN</h2>
        <h4 class="dialog">Sign In into your Account</h4><br><br>

        <div class="container">
            
            <div class="row"> 
                    <!-- <form method="POST" action="{% url 'student:student_home' %}"> -->
                        <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <input type="email" name="s_email" id="email" class="form-control" placeholder="Email Address">     
                                <span id="email_err" style="margin-left: 10px;"></span>    
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-lg-6">
                                <input type="text"  name="s_password" id="pswrd" class="form-control" placeholder="Password">  
                                <span id="pswrd_err" style="margin-left: 10px;"></span>    
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-lg-6">
                                <button type="submit" id="id1" class="btn1 mt-3 mb-5" onclick="return student_login()" >Login</button>  
                            </div>
                            <span style="color: red; margin-left:50px">{{error}}</span>
                        </div>
                        <div class="aaaa col-lg-12">
                           <a href="{% url 'forgotpw' %}">Forgot Password</a><br><br>
                           
                        </div>


                    </form>

            </div>
        </div>
    </section>
    
</body>
</html>

student/templates/student/student_master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://blog.getbootstrap.com/2021/01/07/bootstrap-icons-1-3-0/"></script>
</head>
<style>
    *{
        margin: 0;
        padding: 0;
        box-shadow: border-box;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }
    body{
        width: 100%;
        /* background: linear-gradient(to right,hsl(204, 81%, 69%) 0%,#30f36b 100%); */
        background-image: url("{% static 'images/cls.webp' %}");
        position: relative;
    }
    #menu{
        background-color: black;
        width: 400px;
        height: 100%;
    }
    #menu .logo{
        display: flex;
        align-items: center;
        color: azure;
        padding: 30px 0 0 30px;

    }
    #menu .logo img{
        width: 100px;
        margin-right: 15px;
    }
    #menu .items{
        margin-top: 10px;
    }
    #menu .items li{
        list-style: none;
        padding: 55px;
    }
    #menu .items li a{
        text-decoration: none;
        color: rgb(243, 243, 232);
       
    }
    #menu .items li:hover{
        background: rgb(27, 26, 26);
    }
    .ars{
        /* background-color: hsl(165, 73%, 78%); */
        background-color: rgba(255, 255, 255, 0.686);
        width: 900px;
        height: 630px;
        box-shadow: 0 50px 50px 0px rgba(0,0,0,0.1);
        border-radius: 20px;
        margin-left: 140px;
    }
    .form{
        border-spacing: 15px;
        border-collapse: separate;
        padding-left: 200px;
        padding-top: 20px;
        
    }
    .head{
      padding-top: 30px;
      text-align: center;
    }
    .des{
        padding-top: 50px;
        padding-left: 40px;
    }
    .second{
       
        margin-top: 40px;
    }
    .third{
        margin-top: 60px;
        
        
        
    }
    svg{
        margin-left: 400px;
        /* font-size: 200px; */
        height: 30px;
        width: 30px;
        margin-top: 20px;
        color: black;
    }
   
    
   
</style>
<body>
    
    <div class="row">
        <div class="col-md-3">
           <section id="menu">
               
             <div class="logo">
                <img src="{% static 'images/face.jpg' %}">
                <h2>Attendance Marking Using Face Recognition</h2><hr>
             </div>
             <div class="items">
                <li><a href="{% url 'student:student_home' %}">DashBoard</a></li>
                <li><a href="{% url 'student:student_profile' %}">Profile</a></li>
                <li><a href="{% url 'student:student_authentication' %}">Autentication code</a></li>
                <li><a href="">Log Out</a></li>
             </div>
           </section>
        </div>
        <div class="col-md-4">
            <div class="ars col-md-5"style="margin-top: 70px;">
                <section class="">
                    {% block student_content %}
                    
                    {% endblock %}
                </section>
            </div>
        </div>
        <div class="col-md-1">
           
          <a href="{% url 'student:student_msg' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
            <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
          </svg></a>
              
        </div>
        <div class="col-md-1">
            <a href="{% url 'student:student_chat' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
              </svg></a>
        </div>
        
    </div>



   

   
    
  

</body>
</html>

student/templates/student/student_msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<style>
  body{
    background-color: rgb(205, 201, 201);
  }
    .contactus{
        max-width: 1000px;
        height: 500px;
        margin: 50px auto; 
        position: relative;
        box-shadow: 0 50px 50px 0px rgba(0,0,0,0.1);
    }
    .contactus .title{
        text-align: center;
        line-height: 40px;
        padding-bottom: 20px;
        padding-top: 20px;
        color: white;
        background: black;
    }
    .contactus .dialog{
        text-align: center;
        color: grey;
        justify-content: center;
       
    }

</style>
<body>
     <div class="container-fluid">
  <div class="row">
    
 </div>
</div>




    <section class="contactus">
        <h2 class="title">View your messages</h2>
        <p class="dialog"></p>
        <div class="container">
            <div class="row">
                <table class="table table-striped">
                    <thead>
                      <tr>
                        <th scope="col">No</th>
                        <th scope="col">Sender</th>
                        <th scope="col">Messages</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for d in data %}
                      <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{d.faculty_id.name|capfirst}}</td>
                        <td>{{d.ac_authentication}}</td>
                      </tr>

                      {% endfor %}
                      {% comment %} <tr>
                        <th scope="row">2</th>
                        <td></td>
                        <td></td>
                                                              
                      </tr>
                      <tr>
                        <th scope="row">3</th>
                        <td></td>
                        <td></td>
                        
                      </tr>
                      <tr>
                        <th scope="row">4</th>
                        <td></td>
                        <td></td>
                       
                      </tr>
                      <tr>
                        <th scope="row">5</th>
                        <td></td>
                        <td></td>
                       
                      </tr>
                      <tr>
                        <th scope="row">6</th>
                        <td></td>
                        <td></td>
                        
                      </tr> {% endcomment %}
                    </tbody>
                  </table>
            </div>
        </div>

    </section>
    
</body>
</html>

student/templates/student/student_profile.html
{% extends 'student/student_master.html' %}
{% block student_content %}
<table class="form"> 
  <form>
    <h2 class="head" style="font-weight: bolder;
    font-family: 'Times New Roman', Times, serif;
    text-align: center;   
    padding-top: 40px;"><b>Please Check Your Details...</b></h2>
      <tr>
        <td><label for="">Name:</label></td>
        <td><input type="" class="form-control" name="" id="" placeholder="{{stu.name}}"></td>
      </tr>
      <tr>
        <td><label for="">Enrollment Number:</label></td>
        <td><input type="" class="form-control" name="" id=""  placeholder="{{stu.eno}}"> </td>
      </tr>
      <tr>
        <td><label for="">DOB:</label></td>
        <td><input type="" class="form-control" name="" id=""  placeholder="{{stu.dob}}"></td>
      </tr>
      <tr>
        <td><label for="">Email:</label></td>
        <td><input type="" class="form-control"  name="" id=""  placeholder="{{stu.email}}"></td>
      </tr> 
      <tr>
        <td><label for="">Phone Number:</label></td>
        <td><input type="" class="form-control"  name="" id=""  placeholder="{{stu.phone}}"></td>
      </tr>
      <tr>
        <td><label for="">Gender:</label></td>
        <td><input type="" class="form-control"  name="" id=""  placeholder="{{stu.gender}}"></td>
      </tr>
      <tr>
        <td><label for="">Semester:</label></td>
        <td><input type="" class="form-control" name="" id=""  placeholder="{{stu.semester}}"></td>
      </tr>
      <tr>
        <td><label for="">Department:</label></td>
        <td><input type="" class="form-control" name="" id=""  placeholder="{{stu.dpt}}"></td>
      </tr>
      
      <tr>
        <td> <button type="button" class="btn btn-dark">Capture Image</button></td>
        <!-- <td> <button type="button" class="btn btn-success">Capture Image</button></td> -->
      </tr>
     
     

 </form>
</table>
{% endblock %}