amufr/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('admins.urls')),
    path('student/',include('student.urls',namespace="student")),
    path('faculty/',include('faculty.urls',namespace="faculty"))

]

faculty/urls.py
from . import views
from django.urls import path

app_name="faculty"

urlpatterns=[
    path('login_faculty',views.login_faculty,name="login_faculty"),
    path('forgotpwF',views.forgotpwF,name="forgotpwF"),
    path('faculty_home',views.faculty_home,name="faculty_home"),
    path('faculty_profile',views.faculty_profile,name="faculty_profile"),
    path('faculty_authentication',views.faculty_authentication,name="faculty_authentication"),
    path('student_register',views.student_register,name="student_register"),
    path('student_details',views.student_details,name="student_details"),
    path('search_student',views.search_student),
    path('attendance_date',views.attendance_date,name="attendance_date"),
    path('attendance_month',views.attendance_month,name="attendance_month"),
    path('faculty_msg',views.faculty_msg,name="faculty_msg"),
    path('faculty_chat_student',views.faculty_chat_student,name="faculty_chat_student"),
    path('faculty_chat_admin',views.faculty_chat_admin,name="faculty_chat_admin"),
]

faculty/models.py
from django.db import models

from admins.models import Faculty

# Create your models here.
class Student(models.Model):
    name=models.CharField(max_length=20)
    eno=models.BigIntegerField()
    dob=models.CharField(max_length=25)
    gender=models.CharField(max_length=20)
    dpt=models.CharField(max_length=20)
    semester=models.CharField(max_length=20)
    email=models.CharField(max_length=30)
    phone=models.BigIntegerField()
    password=models.CharField(max_length=30)


    class Meta:
        db_table="student"






class FacultyAuthentication(models.Model):
    ac_dpt=models.CharField(max_length=20)
    ac_sem=models.CharField(max_length=20)
    ac_subject=models.CharField(max_length=20)
    ac_authentication=models.CharField(max_length=20)
    faculty_id = models.ForeignKey(Faculty, on_delete=models.CASCADE)


    class Meta:
        db_table="authentication_fac"

faculty/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from admins.models import Faculty
from faculty.models import Student
from faculty.models import FacultyAuthentication

# Create your views here.





def login_faculty(request):
    error=''
    if request.method=='POST':
        fac_email=request.POST['f_email']
        fac_password=request.POST['f_password']
        try:
            user_data=Faculty.objects.get(email=fac_email,password=fac_password)
            request.session['faculty_id']=user_data.id
            return redirect('faculty:faculty_home')
        except:
           error="invalid username or password"

    return render(request,'faculty/faculty_login.html',{'error':error})








def forgotpwF(request):
    return render(request,'faculty/faculty_forgot_pw.html')









def faculty_home(request):
    faculty_name=request.session['faculty_id']
    faculty_display=Faculty.objects.get(id=faculty_name)
    return render(request,'faculty/faculty_home.html',{'fac':faculty_display})








def faculty_profile(request):
    faculty_name=request.session['faculty_id']
    faculty_display=Faculty.objects.get(id=faculty_name)
    return render(request,'faculty/faculty_profile.html',{'fac':faculty_display})







def faculty_authentication(request):
    if request.method=="POST":
        current_user = request.session['faculty_id']
        user_obj = Faculty.objects.get(id=current_user)

        # current_display = FacultyAuthentication.objects.get(id=current_user)
        fac_ac_dpt=request.POST['ac_department']
        fac_ac_sem=request.POST['ac_semester']
        fac_ac_subject=request.POST['ac_sub']
        fac_ac_code=request.POST['ac_code']

        fac_ac_obj=FacultyAuthentication(ac_dpt=fac_ac_dpt,ac_sem=fac_ac_sem,ac_subject=fac_ac_subject,ac_authentication=fac_ac_code,faculty_id=user_obj)
        fac_ac_obj.save()
    return render(request,'faculty/faculty_authentication.html')







def student_register(request):
    if request.method=='POST':
        stu_name=request.POST['s_name']
        stu_eno=request.POST['s_eno']
        stu_dob=request.POST['s_dob']
        stu_gender=request.POST['s_gender'] 
        stu_dpt=request.POST['s_dpt'] 
        stu_sem=request.POST['s_sem']
        stu_email=request.POST['s_email']  
        stu_phone=request.POST['s_phone'] 
        stu_password=request.POST['s_password']

        stu_obj=Student(name=stu_name,eno=stu_eno,dob=stu_dob,gender=stu_gender,dpt=stu_dpt,semester=stu_sem,email=stu_email,phone=stu_phone,password=stu_password)
        stu_obj.save()
    return render(request,'faculty/student_register.html')






def student_details(request):
    return render(request,'faculty/student_details.html')







def search_student(request):
    if request.method == 'POST':
        dept = request.POST['dropdown1']
        sem = request.POST['dropdown2']
        print(sem)
        print(dept)

    student_data = Student.objects.filter(dpt=dept, semester=sem)
    return render(request,'faculty/student_details.html',{"stu_details":student_data})







    

def attendance_date(request):
    return render(request,'faculty/student_attendanceD.html')

def attendance_month(request):
    return render(request,'faculty/student_attendanceM.html')




# def faculty_msg(request):
#     faculty_name=request.session['faculty_id']
#     faculty_display=FacultyAuthentication.objects.get(id=faculty_name)
#     return render(request,'faculty/faculty_msg.html',{'fac':faculty_display})



def faculty_msg(request):
    return render(request,'faculty/faculty_msg_student.html')

def faculty_chat_student(request):
    return render(request,'faculty/faculty_chat_student.html')

def faculty_chat_admin(request):
    return render(request,'faculty/faculty_chat_admin.html')

faculty/templates/faculty_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script> 
</head>
<style>
    .head{
        max-width: 1000px;
        margin: 50px auto; 
        position: relative;
        box-shadow: 0 50px 50px 0px rgba(0,0,0,0.1);
    }
    .head .title{
        font-style: initial;
        text-align: center;
        line-height: 40px;
        padding-bottom: 20px;
        padding-top: 20px;
        color:  black;
        background: linear-gradient(to right,hsl(204, 81%, 69%) 0%,#daf0b8 100%);
        
    }
    .head .dialog{
        color: grey;
        text-align: center;
    }  
    img{
        border-radius: 30px;
        height: 100px;
        width: 100px;
        justify-content: center;
        text-align: center;
    }
    .form-row{
        background-color: white;
        justify-content: center; 
       
    }
    .form-row{
        position: relative;
        margin: 20px 20px;
        justify-content: center;
        padding-left: 300px;
        padding-top: 0px;
    }
    .form-row .btn1{
        border: none;
        outline: none;
        height: 50px;
        width: 100%;
        background-color: black;
        color: white;
        border-radius: 4px;
        font-weight: bold;
    }
    .form-row .btn1:hover{
        background: white;
        border: 1px solid;
        color: black;
    }
    .aaaa{
        padding-left: 350px;
    }
       
    

</style>
<body>
    <section class="head">
        <h2 class="title">FACULTY LOGIN</h2>
        <h4 class="dialog">Sign In into your Account</h4><br><br>

        <div class="container">
            <!-- <div class="row">
                <div class="col-lg-12">
                    <img src="images/fac.jpg" class="img-fluid" alt="">
                </div>
            </div>    -->
            <div class="row"> 
                    <form action="">
                        <div class="form-row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <input type="email" class="form-control" placeholder="Email Address">          
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-lg-6">
                                <input type="Password" class="form-control" placeholder="Password">          
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-lg-6">
                                <button class="btn1 mt-3 mb-5">Login</button>          
                            </div>
                        </div>
                        <div class="aaaa col-lg-12">
                           <a href="{% url 'faculty:forgotpwF' %}">Forgot Password</a>
                           <p>Don't have an account? <a href="{% url 'faculty:registerF' %}">Register Here</a></p>
                        </div>


                    </form>

            </div>
        </div>
    </section>
    
</body>
</html>

faculty/templates/faculty_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script> 
</head>
<style>
    
    /* h1{
        color: black;
        text-align: center;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    } */
    .myform{
        background: linear-gradient(to right,hsl(204, 81%, 69%) 0%,#daf0b8 100%);
        font-family: Arial, Helvetica, sans-serif;
        height: 100%;
        width: 100%;
        padding: 25px 25px 25px 25px;
        border-radius: 20px;

    }
    .myform .head{
        color: black;
        text-align: center;
        font-family: Arial, Helvetica, sans-serif;
        font-weight: 600;
    }
</style>
<body>
    <!-- <br><br>
    <h1>Student Registration Form</h1>
    <br><br> -->
    <br><br><br><br>

    <div class="container">
        <div class="myform">
            <form class="" action="" method="post">

                 <div class="row">
                     <h1 class="head">Faculty Registration Form</h1>
                 </div><br><br>


                


                <div class="row">
                    <div class="form-group col-6">
                        <label for="">Name :</label>
                        <input type="text" name="" id="" class="form-control">
                    </div>
                    <div class="form-group col-6">
                        <label for="">Department :</label>
                        <select class="form-control" name="" id="">
                            <option value="">CSE</option>
                            <option value="">CE</option>
                            <option value="">ECE</option>
                            <option value="">EEE</option>
                            <option value="">ME</option>
                        </select>
                    </div>
                   
                </div>



                <div class="row">
                    <div class="form-group col-6">
                        <label for="">Gender :</label>
                        <select class="form-control" name="" id="">
                            <option value="">Male</option>
                            <option value="">Female</option>
                        </select>
                    </div>
                    <div class="form-group col-6">
                        <label for="">DOB :</label>
                        <input type="date" name="" id="" class="form-control">
                    </div>
                </div>

                


                <div class="row">
                    <div class="form-group col-6">
                        <label for="">Email</label>
                        <input type="text" name="" id="" class="form-control">
                    </div>
                    <div class="form-group col-6">
                        <label for="">Phone Number</label>
                        <input type="text" name="" id="" class="form-control">
                    </div>
                </div>



                <div class="row">
                    <div class="form-group col-6">
                        <label for="">Password</label>
                        <input type="password" name="" id="" class="form-control">
                    </div>
                    <div class="form-group col-6">
                        <label for="">Confirm Password</label>
                        <input type="password" name="" id="" class="form-control">
                    </div>
                </div><br><br><br>

                <div class="row">
                    <div class="form-group col-6">
                        <button class="btn btn-success">Submit</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
    
</body>
</html>