amufr/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('admins.urls')),
    path('student/',include('student.urls',namespace="student")),
    path('faculty/',include('faculty.urls',namespace="faculty"))

]

faculty/urls.py
from . import views
from django.urls import path

app_name="faculty"

urlpatterns=[
    path('login_faculty',views.login_faculty,name="login_faculty"),
    path('forgotpwF',views.forgotpwF,name="forgotpwF"),
    path('faculty_home',views.faculty_home,name="faculty_home"),
    path('faculty_profile',views.faculty_profile,name="faculty_profile"),
    path('faculty_authentication',views.faculty_authentication,name="faculty_authentication"),
    path('student_register',views.student_register,name="student_register"),
    path('student_details',views.student_details,name="student_details"),
    path('search_student',views.search_student),
    path('attendance_date',views.attendance_date,name="attendance_date"),
    path('attendance_month',views.attendance_month,name="attendance_month"),
    path('faculty_msg',views.faculty_msg,name="faculty_msg"),
    path('faculty_chat_student',views.faculty_chat_student,name="faculty_chat_student"),
    path('faculty_chat_admin',views.faculty_chat_admin,name="faculty_chat_admin"),
]

faculty/models.py
from django.db import models

from admins.models import Faculty

# Create your models here.
class Student(models.Model):
    name=models.CharField(max_length=20)
    eno=models.BigIntegerField()
    dob=models.CharField(max_length=25)
    gender=models.CharField(max_length=20)
    dpt=models.CharField(max_length=20)
    semester=models.CharField(max_length=20)
    email=models.CharField(max_length=30)
    phone=models.BigIntegerField()
    password=models.CharField(max_length=30)


    class Meta:
        db_table="student"






class FacultyAuthentication(models.Model):
    ac_dpt=models.CharField(max_length=20)
    ac_sem=models.CharField(max_length=20)
    ac_subject=models.CharField(max_length=20)
    ac_authentication=models.CharField(max_length=20)
    faculty_id = models.ForeignKey(Faculty, on_delete=models.CASCADE)


    class Meta:
        db_table="authentication_fac"

faculty/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from admins.models import Faculty
from faculty.models import Student
from faculty.models import FacultyAuthentication

# Create your views here.





def login_faculty(request):
    error=''
    if request.method=='POST':
        fac_email=request.POST['f_email']
        fac_password=request.POST['f_password']
        try:
            user_data=Faculty.objects.get(email=fac_email,password=fac_password)
            request.session['faculty_id']=user_data.id
            return redirect('faculty:faculty_home')
        except:
           error="invalid username or password"

    return render(request,'faculty/faculty_login.html',{'error':error})








def forgotpwF(request):
    return render(request,'faculty/faculty_forgot_pw.html')









def faculty_home(request):
    faculty_name=request.session['faculty_id']
    faculty_display=Faculty.objects.get(id=faculty_name)
    return render(request,'faculty/faculty_home.html',{'fac':faculty_display})








def faculty_profile(request):
    faculty_name=request.session['faculty_id']
    faculty_display=Faculty.objects.get(id=faculty_name)
    return render(request,'faculty/faculty_profile.html',{'fac':faculty_display})







def faculty_authentication(request):
    if request.method=="POST":
        current_user = request.session['faculty_id']
        user_obj = Faculty.objects.get(id=current_user)

        # current_display = FacultyAuthentication.objects.get(id=current_user)
        fac_ac_dpt=request.POST['ac_department']
        fac_ac_sem=request.POST['ac_semester']
        fac_ac_subject=request.POST['ac_sub']
        fac_ac_code=request.POST['ac_code']

        fac_ac_obj=FacultyAuthentication(ac_dpt=fac_ac_dpt,ac_sem=fac_ac_sem,ac_subject=fac_ac_subject,ac_authentication=fac_ac_code,faculty_id=user_obj)
        fac_ac_obj.save()
    return render(request,'faculty/faculty_authentication.html')







def student_register(request):
    if request.method=='POST':
        stu_name=request.POST['s_name']
        stu_eno=request.POST['s_eno']
        stu_dob=request.POST['s_dob']
        stu_gender=request.POST['s_gender'] 
        stu_dpt=request.POST['s_dpt'] 
        stu_sem=request.POST['s_sem']
        stu_email=request.POST['s_email']  
        stu_phone=request.POST['s_phone'] 
        stu_password=request.POST['s_password']

        stu_obj=Student(name=stu_name,eno=stu_eno,dob=stu_dob,gender=stu_gender,dpt=stu_dpt,semester=stu_sem,email=stu_email,phone=stu_phone,password=stu_password)
        stu_obj.save()
    return render(request,'faculty/student_register.html')






def student_details(request):
    return render(request,'faculty/student_details.html')







def search_student(request):
    if request.method == 'POST':
        dept = request.POST['dropdown1']
        sem = request.POST['dropdown2']
        print(sem)
        print(dept)

    student_data = Student.objects.filter(dpt=dept, semester=sem)
    return render(request,'faculty/student_details.html',{"stu_details":student_data})







    

def attendance_date(request):
    return render(request,'faculty/student_attendanceD.html')

def attendance_month(request):
    return render(request,'faculty/student_attendanceM.html')




# def faculty_msg(request):
#     faculty_name=request.session['faculty_id']
#     faculty_display=FacultyAuthentication.objects.get(id=faculty_name)
#     return render(request,'faculty/faculty_msg.html',{'fac':faculty_display})



def faculty_msg(request):
    return render(request,'faculty/faculty_msg_student.html')

def faculty_chat_student(request):
    return render(request,'faculty/faculty_chat_student.html')

def faculty_chat_admin(request):
    return render(request,'faculty/faculty_chat_admin.html')

faculty/templates/faculty/faculty_authentication.html
{% extends 'faculty/faculty_master.html' %}
{% block faculty_content %}
 <table class="form">
                <form method="POST" enctype="multipart/form-data" action="">
                    {% csrf_token %}
                    <h2 class="head" style="font-weight: bolder;font-family: 'Times New Roman', Times, serif;text-align: center;padding-top: 40px;"><b> Generate Authentication Code</b></h2>
                       
                        <tr>
                            <p class="des">Dear faculty, please generate 4 digit authentication code specifing the name of your subject. For example(py2208).This authentication code  generated by the faculty helps  to save the system from any student fraudulent activities.</p>
                        </tr>
                       
                          <tr>
                            <td><label for="" style="padding-bottom: 10px;">Department:</label></td>
                         
                            <td>
                             <select style="margin-bottom: 10px;" class="form-control" name="ac_department" id="">
                                 
                                 <option value="cse">CSE</option> 
                                 <option value="ece">ECE</option> 
                             </select>
                            </td>
                         </tr>

                         <tr >
                            <td><label for="">Semester:</label></td>
                         
                            <td>
                             <select class="form-control" name="ac_semester" id="">
                                 <option value="1">1</option>
                                 <option value="2">2</option>
                                 
                             </select>
                            </td>
                         </tr>
                    
                        <tr>
                           <td><label for="">Subject:</label></td>
                        
                           <td>
                            <select class="form-control" name="ac_sub" id="">
                                <option value="Python">Python</option>
                                <option value="C">C</option>
                                <option value="C++">C++</option>
                                <option value="Java">Java</option>
                                <option value="Electronics">Electronics</option>
                                <option value="Electrical">Electrical</option>
                                <option value="Mp&Mc">Mp & Mc</option>
                                <option value="Instrumental">Instrumentation</option>
                                
                            </select>
                           </td>
                        </tr>

                       
                        <tr>
                           <td><label for="" class="second">Authentication Code:</label></td>
                           <td><input type="text" class=" second form-control" name="ac_code" id=""></td>
                        </tr>
                        <tr>
                           
                            <td> <button type="submit" style="margin-left: 160px;" class="third btn btn-dark">Sent to Students</button></td>
                          
                        </tr>
                </form>
            </table>
             
{% endblock %}       

faculty/templates/faculty/faculty_chat_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="icon" type="images/x-icon" href="{% static 'images/metro1.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/reply.css' %}">

    <style>
       
body{
    margin: 0;
    
    background-image: url("{% static 'images/cls.webp' %}");
}

h1{
    font-weight: bolder;
    font-family: 'Times New Roman', Times, serif;
    /* text-align: center;    */
    /* padding-top: 40px;  */
    margin-left:25px ;
}
h3{
    margin-left: 135px;
    margin-top: 40px;
    color: black;
    font-weight: 700;
}
p{
    text-decoration: none;
    font-size: 20px;
    font-weight: 600;
    margin-top: 40px;
    text-align: center;
    font-family: 'Times New Roman', Times, serif;
}

.main{

    width: 800px;
    height: 600px;
    margin-left: 380px;
    margin-top: 50px;
    background-color: rgba(255, 255, 255, 0.686);
    
}
 .table{
    border: none;
    width: 500px;
    margin-left: 130px;
    margin-top: 70px;
    border: none;
}
 

textarea{
    width: 400px;
    height: 100px;
    background-color: rgba(255, 255, 255, 0.518);
    border: solid 1px white;
}
.btn{
    background-color: black;
    color: #fff;
    width: 200px;
    margin-top: 30px;
}
.btn:hover{
    background-color: #fff;
    color: black;
    border: solid 2px black;
}
.btn1{
    margin-left: 210px;
   
}
.btn{
  margin-left: 300px;
}
     
input{
   border: solid 1px white;
   width: 400px;
}
     
td{
    font-size: large;
    font-weight: 400;
}   
    </style>
</head>
<body>
    <div class="body">
       <div class="shadow main">
           <div class="row">
            <a href="{% url 'faculty:faculty_chat_student' %}"><h3>Contact Student</h3></a>   
             <a href=""><h3>Contact Admin</h3></a>
           </div>
             
             <p>Talk with admin to resolve your problems.</p>
            
             <table class="table">
                <!-- <thead>
                  <tr>
                    <td >Name of student</td>
                    <td >:</td>
                    <td ><input type="text"></td>
                    
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Email</td>
                    <td>:</td>
                    <td><input type="text"></td>
                    
                  </tr> -->
                  <tr>
                    <td>Message</td>
                    <td>:</td>
                    <td><textarea name="" id="" cols="30" rows="10"></textarea></td>
                    
                  </tr>
                 
                </tbody>
              </table>
          <a href="" class="btn btn-light">Send</a>
         </div>
    </div>
</body>
</html>

faculty/templates/faculty/faculty_chat_student.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="icon" type="images/x-icon" href="{% static 'images/metro1.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/reply.css' %}">

    <style>
       
body{
    margin: 0;
    
    background-image: url("{% static 'images/cls.webp' %}");
}

h1{
    font-weight: bolder;
    font-family: 'Times New Roman', Times, serif;
    /* text-align: center;    */
    /* padding-top: 40px;  */
    margin-left:25px ;
}
h3{
    margin-left: 135px;
    margin-top: 40px;
    color: black;
    font-weight: 700;
}
p{
    text-decoration: none;
    font-size: 20px;
    font-weight: 600;
    margin-top: 40px;
    text-align: center;
    font-family: 'Times New Roman', Times, serif;
}

.main{

    width: 800px;
    height: 600px;
    margin-left: 380px;
    margin-top: 50px;
    background-color: rgba(255, 255, 255, 0.686);
    
}
 .table{
    border: none;
    width: 500px;
    margin-left: 130px;
    margin-top: 70px;
    border: none;
}
 

textarea{
    width: 400px;
    height: 100px;
    background-color: rgba(255, 255, 255, 0.518);
    border: solid 1px white;
}
.btn{
    background-color: black;
    color: #fff;
    width: 200px;
    margin-top: 30px;
}
.btn:hover{
    background-color: #fff;
    color: black;
    border: solid 2px black;
}
.btn1{
    margin-left: 210px;
   
}
.btn{
  margin-left: 300px;
}
     
input{
   border: solid 1px white;
   width: 400px;
}
     
td{
    font-size: large;
    font-weight: 400;
}   
    </style>
</head>
<body>
    <div class="body">
       <div class="shadow main">
           <div class="row">
            <a href=""><h3>Contact Student</h3></a>   
             <a href="{% url 'faculty:faculty_chat_admin' %}"><h3>Contact Admin</h3></a>
           </div>
             
             <p>Talk with students and admin to resolve your problems.</p>
            
             <table class="table">
                <thead>
                  <tr>
                    <td >Name of student</td>
                    <td >:</td>
                    <td ><input type="text"></td>
                    
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Email</td>
                    <td>:</td>
                    <td><input type="text"></td>
                    
                  </tr>
                  <tr>
                    <td>Message</td>
                    <td>:</td>
                    <td><textarea name="" id="" cols="30" rows="10"></textarea></td>
                    
                  </tr>
                 
                </tbody>
              </table>
          <a href="" class="btn btn-light">Send</a>
         </div>
    </div>
</body>
</html>

faculty/templates/faculty/faculty_master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Faculty</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</head>
<style>
    *{
        margin: 0;
        padding: 0;
        box-shadow: border-box;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }
    body{
        width: 100%;
        /* background: linear-gradient(to right,hsl(204, 78%, 64%) 0%,#daf0b8 100%); */
        background-image: url("{% static 'images/qqqq.jpg' %}");
        position: relative;
    }
    #menu{
        background-color: black;
        width: 400px;
        height: 100%;
    }
    #menu .logo{
        display: flex;
        align-items: center;
        color: azure;
        padding: 30px 0 0 30px;

    }
    #menu .logo img{
        width: 100px;
        margin-right: 15px;
    }
    #menu .items{
        margin-top: 80px;
    }
    #menu .items li{
        list-style: none;
        padding: 30px;
    }
    #menu .items li a{
        text-decoration: none;
        color: rgb(243, 243, 232);
       
    }
    #menu .items li:hover{
        background: rgb(27, 26, 26);
    }
    .ars{
        /* background-color: hsl(204, 76%, 73%); */
        background-color: rgba(255, 255, 255, 0.686);
        width: 900px;
        height: 680px;
        box-shadow: 0 50px 50px 0px rgba(0,0,0,0.1);
        border-radius: 20px;
        margin-left: 100px;
    }
    .form{
        border-spacing: 15px;
        border-collapse: separate;
        padding-left: 200px;
        padding-top: 20px;
        
        
    }
    .head{
      padding-top: 30px;
      text-align: center;
    }
    
    .des{
        padding-top: 40px;
        padding-left: 40px;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }
    .second{
       
        margin-top: 50px;
    }
    .third{
        margin-top: 40px;
        
        
    }
    svg{
    margin-left: 400px;
    /* font-size: 200px; */
    height: 30px;
    width: 30px;
    margin-top: 20px;
    color: black;
}

  
    
   
</style>
<body>
    <div class="row">
        <div class="col-md-3">
           <section id="menu">
             <div class="logo">
                <img src="{% static 'images/face.jpg' %}">
                <h2>Attendance Marking Using Face Recognition</h2><hr>
             </div>
             <div class="items">
                <li><a href="{% url 'faculty:faculty_home' %}">  DashBoard</a></li>
                <li><a href="{% url 'faculty:faculty_profile' %}">  Profile</a></li>
                <li><a href="{% url 'faculty:faculty_authentication' %}">Authentication code</a></li>
                <li><a href="{% url 'faculty:student_details' %}">Student Details</a></li>
                
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                      View Attendance Sheets
                    </a>
                    <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'faculty:attendance_date' %}">Datewise</a>
                      <a class="dropdown-item" href="{% url 'faculty:attendance_month' %}">Monthwise</a>
                    </div>
                  </li>
                <li><a href="">Log Out</a></li>
             </div>
           </section>
    </div>



   
<div class="col-md-4">
    <div class="ars col-md-5"style="margin-top: 100px;">
        <section class="">
            {% block faculty_content %}
            
            {% endblock %}
        </section>
    </div>
</div>
    <div class="col-md-1">

       
       
        <a href="{% url 'faculty:faculty_msg' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
          <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
        </svg></a>
    </div>
        <div class="col-md-1">
            <a href="{% url 'faculty:faculty_chat_student' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
              </svg></a>
        </div>
        
            
     
  

</body>
</html>

faculty/templates/faculty/student_details.html
{% extends 'faculty/faculty_master.html' %}
{% block faculty_content %}

<style>
  #btn{
    color: #fff;
    margin-top: 350px;
    margin-left: 375px;
    text-decoration: none;
    background-color: black;
    position: relative;
  }
</style>
<center><h1 class="heads" style="font-weight: bolder;font-family: 'Times New Roman', Times, serif;text-align: center;padding-top: 20px;">Student Details</h1></center><br>




<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <form class="d-flex" method="POST" action="search_student">
      {% csrf_token %}

     <div class="form-group col-8">
        <label for="">Department :</label>

        <select class="form-control" name="dropdown1" id="dpt" >
    <option selected="selected" disabled>Department</option>

            <option value="cse">CSE</option>
            <option value="ece">ECE</option>
        </select>
        <span id="dpt_span"></span>
    </div>

    <div class="form-group col-8"  style="margin-left: 120px;">
        <label for="" >Semester :</label>
        <select class="form-control" name="dropdown2" id="sem">
            <option value="1">1</option>
            <option value="2">2</option>
        </select>
        <span id="sem_span"></span>
    </div>
    <div>
      <button type="submit"class="btn btn-dark" style="margin-left: 50px; margin-top: 20px;" value="select">Search</button>
    </div>
    
    </form>
  </div>
</nav>






 <table class="table" style="width: 800px; margin-left: 30px; margin-top: 50px;">
  <thead>
    <tr>
      <!-- <th scope="col">id</th> -->
      <th>No.</th>
      <th scope="col">Reg No.</th>
      <th scope="col">Name</th>
      <th scope="col">DOB</th>
      <th scope="col">Email</th>
      <th scope="col">Phone no.</th>
      <th scope="col">Gender</th>
    </tr>
  </thead>
  <tbody>
    {% for i in stu_details %}
    <tr>
      <!-- <td scope="col"></td> -->
      <td>{{forloop.counter}}</td>
      <td scope="col">{{i.eno}}</td>
      <td scope="col">{{i.name}}</td>
      <td scope="col">{{i.dob}}</td>
      <td scope="col">{{i.email}}</td>
      <td scope="col">{{i.phone}}</td>
      <td scope="col">{{i.gender}}</td>
    </tr>
    {% endfor %}
   </tbody>
</table>





<div class="row">
  <div class="">
    <button type="button" id="btn" class="btn btn-dark"><a href="{% url 'faculty:student_register' %}" >Add New Student</a></button>
  </div>
  
</div>
              
{% endblock %}