amufr/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('admins.urls')),
    path('student/',include('student.urls',namespace="student")),
    path('faculty/',include('faculty.urls',namespace="faculty"))

]

faculty/urls.py
from . import views
from django.urls import path

app_name="faculty"

urlpatterns=[
    path('login_faculty',views.login_faculty,name="login_faculty"),
    path('forgotpwF',views.forgotpwF,name="forgotpwF"),
    path('faculty_home',views.faculty_home,name="faculty_home"),
    path('faculty_profile',views.faculty_profile,name="faculty_profile"),
    path('faculty_authentication',views.faculty_authentication,name="faculty_authentication"),
    path('student_register',views.student_register,name="student_register"),
    path('student_details',views.student_details,name="student_details"),
    path('search_student',views.search_student),
    path('attendance_date',views.attendance_date,name="attendance_date"),
    path('attendance_month',views.attendance_month,name="attendance_month"),
    path('faculty_msg',views.faculty_msg,name="faculty_msg"),
    path('faculty_chat_student',views.faculty_chat_student,name="faculty_chat_student"),
    path('faculty_chat_admin',views.faculty_chat_admin,name="faculty_chat_admin"),
]

student/urls.py
from . import views
from django.urls import path

app_name="student"


urlpatterns=[
    path('login_student',views.login_student,name="login_student"),
    path('forgotpwS',views.forgotpwS,name="forgotpwS"),
    path('student_home',views.student_home,name="student_home"),
    path('student_profile',views.student_profile,name="student_profile"),
    path('student_authentication',views.student_authentication,name="student_authentication"),
    path('student_msg',views.student_msg,name="student_msg"),
    path('student_chat',views.student_chat,name="student_chat"),
]

admins/templates/admins/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
<style>
    .head{
        max-width: 1000px;
        margin: 50px auto; 
        position: relative;
        box-shadow: 0 50px 50px 0px rgba(0,0,0,0.1);
    }
    .head .title{
        font-style: initial;
        text-align: center;
        line-height: 40px;
        padding-bottom: 20px;
        padding-top: 20px;
        color:  black;
        background: linear-gradient(to right,hsl(204, 81%, 69%) 0%,#daf0b8 100%);
    }
    /* .head .dialog{
        color: grey;
        text-align: center;
    }   */
    .img{
        
    }
    .para{
      color: grey;
      padding-left: ;
    }
    .btn{
        color: black;
        background-color: hsl(204, 81%, 69%);
        
        
    }
    

</style>
<body>
    <div class="container-fluid">
        <div class="row" style="background-color: hsl(204, 81%, 69%); padding: 10px;">
          <div class="col-lg-12">
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'services' %}">Services</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                Login
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'student:login_student' %}">Student</a>
                <a class="dropdown-item" href="{% url 'faculty:login_faculty' %}">Faculty</a>
                <a class="dropdown-item" href="{% url 'login' %}">Admin</a>
              </div>
            </li>
          </ul>
          </div>
       </div>
      </div>



    <section class="head">
        <h2 class="title">ABOUT US</h2>

        <div class="container">
            <div class="row">
                <div class="para col-md-8 pt-5 pl-5">
                  <h5>Face Recognition Based Attendance System</h5>
                    <p>A system for folding and recognising human faces fast and precisely for attendance.Automated Attendance System has been envisioned for the purpose of reducing the
                        errors that occur in the traditional (manual) attendance taking system. The aim is to automate
                        and make a system that is useful to the organization such as an institute.</p><br>
                        <h6>Face Scanning</h6>
                        <p>Scan the faces of student in few seconds and attendance will be marked</p><br>
                        <h6>User Friendly</h6>
                        <p>Easily accessible ans understandable to the user of our system.</p><br>
                </div>
                <div class="col-md-4">
                    <img src="{% static 'images/face.jpg' %}" alt="" width="300px" height="400px"><br>
                </div>
                <div class="col-lg-3">
                    <button type="button" class="btn btn-link"><a href="https://iopscience.iop.org/article/10.1088/1757-899X/590/1/012049/meta#:~:text=An%20automated%20attendance%20system%20is,day%20activities%20of%20handling%20employees.">Read More</a></button>
                </div>
            </div>
        </div>
        
    </section>
    
</body>
</html>

admins/templates/admins/admin_forgot_pw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
<style>
    
    .head{
        max-width: 600px;
        margin: 50px auto; 
        position: relative;
        box-shadow: 0 50px 50px 0px rgba(0,0,0,0.1);
        padding-top: 50px;
        background: linear-gradient(to right,hsl(204, 81%, 69%) 0%,#daf0b8 100%);
        border-radius: 20px;
        text-align: center;
    }
    .mail{
        line-height: 30px;
        width: 350px;
    }
    

</style>
<body>
    


    <section class="head">
        <h2 class="title">Forgot password</h2>

        <div class="container">
            <div class="row">
                <div class="col-lg-12 pt-5">
                  <input type="text"  class="mail" name="" id="" placeholder="Email/Phone Number">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 pt-5">
                    <button type="button" class="btn btn-success">Change Password</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 pt-5">
                 <a href="" class="link">Back to Sign In</a><br><br><br>
                </div>
            </div>
     </section>
    
</body>
</html>

admins/templates/admins/admin_profile.html
{% extends 'admins/admins_master.html' %}
{% block admins_content %}
<h1 style="font-weight: bolder;font-family: 'Times New Roman', Times, serif;text-align: center;padding-top: 250px;padding-left: 30px;">Welcome Admin</h1>
{% endblock %}

admins/templates/admins/admins_faculty_details.html
{% extends 'admins/admins_master.html' %}
{% block admins_content %}

<center><h1 class="heads" style="font-weight: bolder;font-family: 'Times New Roman', Times, serif;text-align: center;padding-top: 30px;">Faculty Details</h1></center>

<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">
        </a>
    <form class="d-flex"  >
      <input class="form-control me-2" type="search" placeholder="Search by Name" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

<table class="form"> 
    <form>
         <tr>
           <td><label for="">Name:</label></td>
           <td><input type="text" class="form-control" name="" id=""></td>
         </tr>
         <tr>
            <td><label for="">Department:</label></td>
            <td><input type="" class="form-control" name="" id=""></td>
          </tr>
          <tr>
            <td><label for="">Gender:</label></td>
            <td><input type="" class="form-control"  name="" id=""></td>
          </tr>
         
         <tr>
           <td><label for="">DOB:</label></td>
           <td><input type="" class="form-control" name="" id=""></td>
         </tr>
         <tr>
           <td><label for="">Email:</label></td>
           <td><input type="" class="form-control"  name="" id=""></td>
         </tr> 
         <tr>
           <td><label for="">Phone Number:</label></td>
           <td><input type="" class="form-control"  name="" id=""></td>
         </tr>
         <tr>
             <td></td>
         </tr>
         <tr>
            <td></td>
        </tr>
        
         <tr>
           <td><button type="button" class="btn btn-dark"><a href="{% url 'faculty_register' %}" style="color: white; text-decoration: none;">Add New Faculty</a></button></td>
           
         </tr>
        
     </form>
 </table>

 
                   
{% endblock %}

admins/templates/admins/admins_notifications.html
{% extends 'admins/admins_master.html' %}
{% block admins_content %}

<center><h1 class="heads" style="font-weight: bolder;
  font-family: 'Times New Roman', Times, serif;
  text-align: center;   
  padding-top: 30px;">Messages</h1></center><br>
<table class="table shadow">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Email</th>
      <th scope="col">Massage</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td></td>
      <td></td>
      <td><a class="btn btn-dark" href="{% url 'view' %}">view</a></td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td></td>
      <td></td>
      <td><a class="btn btn-dark" href="{% url 'view' %}">view</a></td>
    </tr>
    <tr> <th scope="row">3</th>
      <td></td>
      <td></td>
      <td><a class="btn btn-dark" href="{% url 'view' %}">view</a></td>
    </tr>
    <tr>
      <th scope="row">1</th>
      <td></td>
      <td></td>
      <td><a class="btn btn-dark" href="{% url 'view' %}">view</a></td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td></td>
      <td></td>
      <td><a class="btn btn-dark" href="{% url 'view' %}">view</a></td>
    </tr>
    <tr> <th scope="row">3</th>
      <td></td>
      <td></td>
      <td><a class="btn btn-dark" href="{% url 'view' %}">view</a></td>
    </tr>
  
  </tbody>
</table>

  

                   
{% endblock %}

admins/templates/admins/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<style>
    .contactus{
        max-width: 1000px;
        margin: 50px auto; 
        position: relative;
        box-shadow: 0 50px 50px 0px rgba(0,0,0,0.1);
    }
    .contactus .title{
        text-align: center;
        line-height: 40px;
        padding-bottom: 20px;
        padding-top: 20px;
        color:  black;
        background: linear-gradient(to right,hsl(204, 81%, 69%) 0%,#daf0b8 100%);
    }
    .contactus .dialog{
        text-align: center;
        color: grey;
        justify-content: center;
       
    }

    .contact-form .form-feild{
        position: relative;
        margin: 32px 0px;
       
    }
    .contact-form .input-text{
        display: block;
        width: 100%;
        height: 35px;
        border-width: 0 0 2px 0;
        border-color: hsl(204, 81%, 69%);
        font-size: 20px;
        line-height: 25px;
        font-weight: 400s;
    }
    .contact-form .input-text:focus + .label,
    .contact-form .input-text.not-empty + .label{
        transform: translateY(-25px);
    }
    .contact-form .input-text:focus{
        outline: none;
    }
    .contact-form .label{
        position: absolute;
        left: 20px;
        bottom: 20px;
        font-size: 18px;
        line-height: 25px;
        font-weight: 400;
        color: grey;
        cursor: text;
        transition: transform 0.2s ease-in-out;
    }
    .contact-form .submit-btn{
        display: inline-block;
        color: grey;
        background-color: hsl(204, 81%, 69%);
        width: 200px;
        letter-spacing: 2px;
        padding: 8px 16px;
        border: none;
        

    }
</style>
<body>
     <div class="container-fluid">
  <div class="row" style="background-color: hsl(204, 81%, 69%); padding: 10px;">
    <div class="col-lg-12">
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'services' %}">Services</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
          Login
        </a>
         
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'student:login_student' %}">Student</a>
            <a class="dropdown-item" href="{% url 'faculty:login_faculty' %}">Faculty</a>
            <a class="dropdown-item" href="{% url 'login' %}">Admin</a>
          </div>
      </li>
    </ul>
    </div>
 </div>
</div>




    <section class="contactus">
        <h2 class="title">CONTACT US</h2>
        <p class="dialog">Please get in touch and our expert support team will answer all your questions.We are here to help and answer any question you might have. We look forward to hearing from you. :)</p>
        <div class="container">
            <div class="contact-form row">
                <div class="form-feild col-lg-6">
                    <input id="name" class="input-text" type="text">
                    <label for="name" class="label">Name</label>
                </div>
                <div class="form-feild col-lg-6">
                    <input id="email" class="input-text" type="text">
                    <label for="email" class="label">Email</label>
                </div>
                <div class="form-feild col-lg-6">
                    <input id="phone" class="input-text" type="text">
                    <label for="phone" class="label">Contact Number</label>
                </div>
                <div class="form-feild col-lg-6">
                    <input id="subject" class="input-text" type="text">
                    <label for="subject" class="label">Subject</label>
                </div>
                <div class="form-feild col-lg-">
                    <input id="msg" class="input-text" type="text">
                    <label for="msg" class="label">Message</label>
                </div>
                <div class="form-feild col-lg-12">
                    <input class="submit-btn" type="submit" value="Submit">
                    
                </div>

            </div>
        </div>

    </section>
    
</body>
</html>

admins/templates/admins/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
<style>
  body{
    margin: 0;
    padding: 0;
    background-image: url("{% static 'images/hm.png' %}");
    background-repeat:no-repeat;
    background-size:cover;
    
}
.head{
  text-align: center;
  padding-top: 10px;
  color: rgb(2, 2, 15);
  font-family: 'Times New Roman', Times, serif;
  

}
.nav-link{
  color: black;
}

</style>




<body>
<div class="container-fluid col-md-12">
  <div class="row" style="background-color: hsl(204, 81%, 69%); padding: 10px;">
    <div class="col-lg-12">
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'services' %}">Services</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
          Login
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'student:login_student' %}">Student</a>
          <a class="dropdown-item" href="{% url 'faculty:login_faculty' %}">Faculty</a>
          <a class="dropdown-item" href="{% url 'login' %}">Admin</a>
        </div>
      </li>
        
      
    </ul>
    </div>
 </div>
</div>


<div class="container-fluid">
  <div class="row">
     <div class=" head col-lg-12 col-md-12">
       <h1>Attendance Marking Using Face Recognition</h1>
      
     </div>
  </div>

</div>

<div class="footer">

</div>

    
</body>
</html>

admins/templates/admins/services.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<style>
    .head{
        max-width: 1000px;
        margin: 50px auto; 
        position: relative;
        box-shadow: 0 50px 50px 0px rgba(0,0,0,0.1);
    }
    .head .title{
        text-align: center;
        line-height: 40px;
        padding-bottom: 20px;
        padding-top: 20px;
        color:  black;
        background: linear-gradient(to right,hsl(204, 81%, 69%) 0%,#daf0b8 100%);
    }
    .box{
      border: 1px;
      border-radius: 10px;
      padding-top: 70px;
      padding-left: 100px;
      padding-right: 100px;
      }
    .sub{
      text-align: center;
      justify-content: center;
      color: grey;
    } 
    .para{
      text-align: center;
      color: grey;
    } 
</style>
<body>
    <div class="container-fluid">
        <div class="row" style="background-color: hsl(204, 81%, 69%); padding: 10px;">
          <div class="col-lg-12">
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'services' %}">Services</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                  Login
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'student:login_student' %}">Student</a>
                  <a class="dropdown-item" href="{% url 'faculty:login_faculty' %}">Faculty</a>
                  <a class="dropdown-item" href="{% url 'login' %}">Admin</a>
                </div>
              </li>
          </ul>
          </div>
       </div>
      </div>
  

      <section class="head">
        <h2 class="title">SERVICES</h2>
        <div class="row">
        <div class="box col-lg-4">
          <h5 class="sub">Authentication Code</h5><br>
          <p class="para">An unique authentication code will be generated by the faculty to save the system from any student fraudulent activities. </p><br><br>
        </div>

        <div class="box col-lg-4">
          <h5 class="sub">Generating Attendance Sheet</h5><br>
          <p class="para">As soon as the face will be scanned the attendance of the student will be marked in the attendance sheet.</p>
        </div>

        <div class="box col-lg-4">
          <h5 class="sub">Helps in Time Saving</h5><br>
          <p class="para">The image is scanned in just few seconds resulting in saving time as compared to offline attendance system.</p>
        </div>
      </div>

      </section>
    
</body>
</html>